(function(){
'use strict';
const isObj=v=>v&&typeof v==='object'&&!Array.isArray(v);
function merge(a,b){if(!isObj(a))return b===undefined?a:b;const o={...a};if(!isObj(b))return o;Object.keys(b).forEach(k=>{if(Array.isArray(b[k]))o[k]=b[k];else if(isObj(b[k])&&isObj(a[k]))o[k]=merge(a[k],b[k]);else if(b[k]!==undefined&&b[k]!==null)o[k]=b[k]});return o}
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const text=(s,v,r=document)=>{const e=$(s,r);if(e&&v!==undefined)e.textContent=v};
const html=(s,v,r=document)=>{const e=$(s,r);if(e&&v!==undefined)e.innerHTML=v};
const bg=(s,v,r=document)=>{const e=$(s,r);if(e&&v)e.style.backgroundImage=`url("${String(v).replaceAll('"','\\"')}")`};
function applyGlobal(site,root=document){
 const g=site.global||{},n=site.navigation||{};
 $$('.codimas-logo',root).forEach(i=>{if(g.logo_url)i.src=g.logo_url});$$('.codimas-footer-logo',root).forEach(i=>{if(g.logo_negative_url)i.src=g.logo_negative_url});const fav=$('link[rel*="icon"]',root);if(fav&&g.favicon_url)fav.href=g.favicon_url;
 const top=$('.codimas-topbar',root);if(top){const span=$('.hide-mobile',top);if(span&&g.topbar_left)span.textContent=g.topbar_left;const company=$('a[href*="#empresas"]',top);if(company&&g.topbar_company)company.textContent=g.topbar_company;const contact=$('a[href*="#contacto"]',top);if(contact&&g.topbar_contact)contact.textContent=g.topbar_contact;const track=$('a[href*="seguimiento.html"]',top);if(track&&n.tracking)track.textContent=n.tracking;const admin=$('a[href*="admin/login.html"]',top);if(admin&&n.admin)admin.textContent=n.admin}
 $$('a[href^="mailto:"]',root).forEach(a=>{if(g.sales_email){a.href=`mailto:${g.sales_email}`;if((a.textContent||'').includes('@'))a.textContent=g.sales_email}});$$('a[href^="tel:"]',root).forEach(a=>{if(g.phone){a.href=`tel:${g.phone.replace(/[^+\d]/g,'')}`;if((a.textContent||'').trim().startsWith('+'))a.textContent=g.phone}});
 const nav=$('.codimas-navrow',root);if(nav){[['button',n.products],['a[href*="#categorias"]',n.categories],['a[href*="#empresas"]',n.companies],['a[href*="#servicios"]',n.services],['a[href*="#marcas"]',n.brands],['a[href*="#contacto"]',n.contact]].forEach(([s,v])=>{const e=$(s,nav);if(e&&v)e.textContent=v})}
 const footer=$('.codimas-footer',root);if(footer){const cols=$$('.codimas-footer-grid > div',footer);if(cols[0]){const ps=$$('p',cols[0]);if(ps[0]&&g.legal_name)ps[0].textContent=g.legal_name;if(ps[1]&&g.tagline)ps[1].textContent=g.tagline;if(ps.length===1&&g.tagline)ps[0].textContent=g.tagline}const titles=[g.footer_products_title,g.footer_companies_title,g.footer_help_title,g.footer_contact_title];cols.slice(1,5).forEach((c,i)=>{const h=$('h3',c);if(h&&titles[i])h.textContent=titles[i]});const bottom=$('.codimas-footer-bottom',footer);if(bottom){const spans=$$('span',bottom);if(spans[1]&&g.footer_country)spans[1].textContent=g.footer_country;let credit=$('.codimas-focusone-credit',bottom);if(!credit){credit=document.createElement('span');credit.className='codimas-focusone-credit';bottom.appendChild(credit)}credit.textContent=g.developer_credit||'Sitio diseñado por Focus One SpA'}}
 $$('.codimas-header-actions a[href*="cotizacion.html"]',root).forEach(a=>{if(n.quote)a.textContent=n.quote});$$('a[href*="admin/login.html"]',root).forEach(a=>{if(n.admin)a.textContent=n.admin});
}
function applyHome(site){const h=site.home||{},hero=h.hero||{};text('.codimas-hero-copy .codimas-eyebrow',hero.eyebrow);html('.codimas-hero-title',hero.title_html);text('.codimas-hero-copy .codimas-copy',hero.subtitle);bg('.codimas-hero-image',hero.image_url);const hb=$$('.codimas-hero-copy .codimas-hero-actions a');if(hb[0]){if(hero.primary_text)hb[0].textContent=hero.primary_text;if(hero.primary_href)hb[0].href=hero.primary_href}if(hb[1]){if(hero.secondary_text)hb[1].textContent=hero.secondary_text;if(hero.secondary_href)hb[1].href=hero.secondary_href}
 $$('.codimas-benefit-mini').forEach((e,i)=>{const x=h.benefits?.[i];if(x){text('strong',x.title,e);text('span',x.text,e)}});const heads=$$('.codimas-section-head');if(heads[0]){text('.codimas-eyebrow',h.categories?.eyebrow,heads[0]);html('.codimas-section-title',h.categories?.title_html,heads[0]);text('.codimas-link-arrow',h.categories?.link_text,heads[0])}if(heads[1]){text('.codimas-eyebrow',h.products?.eyebrow,heads[1]);html('.codimas-section-title',h.products?.title_html,heads[1]);text('.codimas-link-arrow',h.products?.link_text,heads[1])}
 $$('.codimas-promo').forEach((node,i)=>{const p=h.promos?.[i];if(!p)return;const im=$('img',node);if(im&&p.image_url)im.src=p.image_url;text('.codimas-eyebrow',p.eyebrow,node);html('h3',p.title_html,node);const ps=$$('.codimas-promo-copy > p',node);if(ps[1]&&p.text!==undefined)ps[1].textContent=p.text;const b=$('.codimas-btn',node);if(b){if(p.button_text)b.textContent=p.button_text;if(p.button_href)b.href=p.button_href}});
 $$('.codimas-trust-item').forEach((e,i)=>{const x=h.trust?.[i];if(x){text('strong',x.title,e);text('span',x.text,e)}});const ent=$('.codimas-enterprise-cta');if(ent&&h.enterprise){const im=$('img',ent);if(im&&h.enterprise.image_url)im.src=h.enterprise.image_url;text('.codimas-eyebrow',h.enterprise.eyebrow,ent);html('h2',h.enterprise.title_html,ent);text('.codimas-copy',h.enterprise.text,ent);const bs=$$('.codimas-btn',ent);if(bs[0]){if(h.enterprise.primary_text)bs[0].textContent=h.enterprise.primary_text;if(h.enterprise.primary_href)bs[0].href=h.enterprise.primary_href}if(bs[1]){if(h.enterprise.secondary_text)bs[1].textContent=h.enterprise.secondary_text;if(h.enterprise.secondary_href)bs[1].href=h.enterprise.secondary_href}}
 const sv=$('#servicios');if(sv&&h.services){text('.codimas-eyebrow',h.services.eyebrow,sv);html('.codimas-section-title',h.services.title_html,sv)}const br=$('#marcas');if(br&&h.brands){text('.codimas-eyebrow',h.brands.eyebrow,br);html('.codimas-section-title',h.brands.title_html,br);text('.codimas-copy',h.brands.text,br)}const ct=$('#contacto');if(ct&&h.contact){text('.codimas-eyebrow',h.contact.eyebrow,ct);text('.codimas-section-title',h.contact.title,ct);const bs=$$('.codimas-btn',ct);if(bs[0]&&h.contact.primary_text)bs[0].textContent=h.contact.primary_text;if(bs[1]&&h.contact.secondary_text)bs[1].textContent=h.contact.secondary_text}}
function applyQuote(site){const q=site.quote||{},hero=$('.codimas-page-hero');if(hero){text('.codimas-eyebrow',q.hero_eyebrow,hero);html('h1',q.hero_title_html,hero);text('.codimas-copy',q.hero_text,hero);bg('.codimas-page-hero-media',q.hero_image_url,hero)}const bc=$('.codimas-breadcrumb');if(bc){const a=$('a',bc),strong=$('strong',bc);if(a&&q.breadcrumb_home)a.textContent=q.breadcrumb_home;if(strong&&q.breadcrumb_current)strong.textContent=q.breadcrumb_current}const aside=$('.codimas-quote-layout aside');if(aside){const first=$('.codimas-panel',aside);if(first){text('.codimas-eyebrow',q.items_eyebrow,first);text('h2',q.items_title,first);const clear=$('#clear-quote-items');if(clear&&q.clear_text)clear.textContent=q.clear_text;const empty=$('#quote-items-empty');if(empty&&q.empty_text)empty.textContent=q.empty_text}const help=$$('.codimas-panel',aside)[1];if(help){text('.codimas-eyebrow',q.help_eyebrow,help);const rows=$$('.codimas-panel-body > div > div',help);rows.forEach((row,i)=>{const x=q.help_items?.[i];if(!x)return;const st=$('strong',row);if(st)st.textContent=x.title;row.childNodes.forEach(node=>{if(node.nodeType===3&&node.textContent.trim())node.textContent=`${x.text}`})})}}
 const fp=$('.codimas-quote-layout > section.codimas-panel');if(fp){text('.codimas-eyebrow',q.form_eyebrow,fp);html('.codimas-section-title',q.form_title_html,fp)}const map=[['#nombre',q.name_label,q.name_placeholder],['#empresa',q.company_label,q.company_placeholder],['#email',q.email_label,q.email_placeholder],['#telefono',q.phone_label,q.phone_placeholder],['#categoria-interes',q.category_label,q.category_placeholder],['#mensaje',q.detail_label,q.detail_placeholder]];map.forEach(([sel,label,ph])=>{const e=$(sel);if(!e)return;const l=e.closest('div')?.querySelector('label');if(l&&label)l.textContent=label;if(e.tagName==='SELECT'){const o=e.querySelector('option[value=""]');if(o&&ph)o.textContent=ph}else if(ph)e.placeholder=ph});const submit=$('#btn-enviar');if(submit&&q.submit_text)submit.textContent=q.submit_text;const form=$('#form-cotizacion');if(form&&q.footer_hint){const ps=$$('p',form);const last=ps[ps.length-1];if(last)last.textContent=q.footer_hint}}
function applyTracking(site){const t=site.tracking||{},hero=$('.codimas-page-hero');if(hero){text('.codimas-eyebrow',t.hero_eyebrow,hero);html('h1',t.hero_title_html,hero);text('.codimas-copy',t.hero_text,hero);bg('.codimas-page-hero-media',t.hero_image_url,hero)}const bc=$('.codimas-breadcrumb');if(bc){const a=$('a',bc),strong=$('strong',bc);if(a&&t.breadcrumb_home)a.textContent=t.breadcrumb_home;if(strong&&t.breadcrumb_current)strong.textContent=t.breadcrumb_current}const sp=$('.tracking-layout aside.codimas-panel');if(sp){text('.codimas-eyebrow',t.search_eyebrow,sp);html('.codimas-section-title',t.search_title_html,sp);const code=$('#tracking-code'),email=$('#tracking-email');if(code){const l=code.closest('div')?.querySelector('label');if(l&&t.code_label)l.textContent=t.code_label;if(t.code_placeholder)code.placeholder=t.code_placeholder}if(email){const l=email.closest('div')?.querySelector('label');if(l&&t.email_label)l.textContent=t.email_label;if(t.email_placeholder)email.placeholder=t.email_placeholder}}const b=$('#tracking-btn');if(b&&t.button_text)b.textContent=t.button_text;const result=$('#tracking-result');if(result){text('.codimas-eyebrow',t.result_eyebrow,result);html('.codimas-section-title',t.result_title_html,result);const labels=$$('h3.text-xs',result);const vals=[t.request_label,t.responses_label,t.attachments_label];labels.forEach((e,i)=>{if(vals[i])e.textContent=vals[i]});const aside=$('aside',result);if(aside){const ps=$$('p.text-xs',aside);if(ps[0]&&t.result_code)ps[0].textContent=t.result_code;if(ps[1]&&t.result_status)ps[1].textContent=t.result_status;if(ps[2]&&t.result_date)ps[2].textContent=t.result_date}}}}
async function load(){const defaults=window.CODIMAS_CMS_DEFAULTS?window.CODIMAS_CMS_DEFAULTS():{},client=window.alanpasttSupabase;let site=defaults;if(client){try{const {data,error}=await client.from('site_content').select('value').eq('key','cms_site').maybeSingle();if(!error&&data?.value)site=merge(defaults,data.value)}catch(e){console.warn('CMS público: usando contenido local.',e)}}window.CODIMAS_CMS=site;applyGlobal(site);const p=(location.pathname||'').toLowerCase();if(p.endsWith('cotizacion.html'))applyQuote(site);else if(p.endsWith('seguimiento.html'))applyTracking(site);else if(!p.includes('/categorias/')&&!p.includes('/admin/'))applyHome(site);window.dispatchEvent(new CustomEvent('codimas:cms-ready',{detail:site}));return site}
window.CODIMAS_CMS_API={deepMerge:merge,applyGlobal,applyHome,applyQuote,applyTracking};window.CODIMAS_CMS_READY=load();
})();